.decl read(v0:symbol, v1:symbol)
.decl write(v0:symbol, v1:symbol)
.decl succ(v0:symbol, v1:symbol, v2:symbol, v3:symbol)
.decl flow(v0:symbol, v1:symbol, v2:symbol, v3:symbol)
.decl defUse(v0:symbol, v1:symbol, v2:symbol, v3:symbol)
.decl symlog_domain_symlog_symbolic_0(v0:symbol)
.decl symlog_domain_symlog_symbolic_1(v0:symbol)
.output defUse
read("r1", "v1").
read("r2", "v1").
read("r3", "v2").
write("w1", "v1").
write("w2", "v2").
write("w3", "v2").
succ("w1", "o1", symlog_binding_symlog_symbolic_0, symlog_binding_symlog_symbolic_1) :- symlog_domain_symlog_symbolic_0(symlog_binding_symlog_symbolic_0), symlog_domain_symlog_symbolic_1(symlog_binding_symlog_symbolic_1).
succ("o1", "r1", symlog_binding_symlog_symbolic_0, symlog_binding_symlog_symbolic_1) :- symlog_domain_symlog_symbolic_0(symlog_binding_symlog_symbolic_0), symlog_domain_symlog_symbolic_1(symlog_binding_symlog_symbolic_1).
succ("o1", "r2", symlog_binding_symlog_symbolic_0, symlog_binding_symlog_symbolic_1) :- symlog_domain_symlog_symbolic_0(symlog_binding_symlog_symbolic_0), symlog_domain_symlog_symbolic_1(symlog_binding_symlog_symbolic_1).
succ("r2", "r3", symlog_binding_symlog_symbolic_0, symlog_binding_symlog_symbolic_1) :- symlog_domain_symlog_symbolic_0(symlog_binding_symlog_symbolic_0), symlog_domain_symlog_symbolic_1(symlog_binding_symlog_symbolic_1).
succ("r3", "w2", symlog_binding_symlog_symbolic_0, symlog_binding_symlog_symbolic_1) :- symlog_domain_symlog_symbolic_0(symlog_binding_symlog_symbolic_0), symlog_domain_symlog_symbolic_1(symlog_binding_symlog_symbolic_1).
flow(X, Y, symlog_binding_symlog_symbolic_0, symlog_binding_symlog_symbolic_1) :- succ(X, Y, symlog_binding_symlog_symbolic_0, symlog_binding_symlog_symbolic_1), symlog_domain_symlog_symbolic_0(symlog_binding_symlog_symbolic_0), symlog_domain_symlog_symbolic_1(symlog_binding_symlog_symbolic_1).
flow(X, Z, symlog_binding_symlog_symbolic_0, symlog_binding_symlog_symbolic_1) :- flow(X, Y, symlog_binding_symlog_symbolic_0, symlog_binding_symlog_symbolic_1), flow(Y, Z, symlog_binding_symlog_symbolic_0, symlog_binding_symlog_symbolic_1), symlog_domain_symlog_symbolic_0(symlog_binding_symlog_symbolic_0), symlog_domain_symlog_symbolic_1(symlog_binding_symlog_symbolic_1).
defUse(W, R, symlog_binding_symlog_symbolic_0, symlog_binding_symlog_symbolic_1) :- write(W, X), flow(W, R, symlog_binding_symlog_symbolic_0, symlog_binding_symlog_symbolic_1), read(R, X), symlog_domain_symlog_symbolic_0(symlog_binding_symlog_symbolic_0), symlog_domain_symlog_symbolic_1(symlog_binding_symlog_symbolic_1).
succ(symlog_binding_symlog_symbolic_0, symlog_binding_symlog_symbolic_1, symlog_binding_symlog_symbolic_0, symlog_binding_symlog_symbolic_1) :- symlog_domain_symlog_symbolic_0(symlog_binding_symlog_symbolic_0), symlog_domain_symlog_symbolic_1(symlog_binding_symlog_symbolic_1).
symlog_domain_symlog_symbolic_0("w1").
symlog_domain_symlog_symbolic_0("r2").
symlog_domain_symlog_symbolic_0("r3").
symlog_domain_symlog_symbolic_0("o1").
symlog_domain_symlog_symbolic_0("symlog_symbolic_0").
symlog_domain_symlog_symbolic_1("o1").
symlog_domain_symlog_symbolic_1("w2").
symlog_domain_symlog_symbolic_1("r1").
symlog_domain_symlog_symbolic_1("symlog_symbolic_1").
symlog_domain_symlog_symbolic_1("r2").
symlog_domain_symlog_symbolic_1("r3").
