import sys

SYMBOLIC_CONSTANT_PREFIX = 'symlog_symbolic_'
BINDING_VARIABLE_PREFIX = 'symlog_binding_'
DOMAIN_PREDICATE_PREFIX = 'symlog_domain_'
RECORD_ARG_PREFIX = '_symlog_record_'
DEFAULT_SOUFFLE_TYPE = 'symbol'
SOUFFLE_SYMBOL = 'symbol'
SOUFFLE_NUMBER = 'number'
SOUFFLE_CONTAINS = 'contains'
SOUFFLE_SUBSTR = 'substr'
SOUFFLE_INTRINSIC_PREDS = {SOUFFLE_CONTAINS, SOUFFLE_SUBSTR}

SOUFFLE_SYMBOL = 'symbol'
SOUFFLE_NUMBER = 'number'
SOUFFLE_LOGICAL_OR = ' lor '
SOUFFLE_CONTAINS = 'contains'
SOUFFLE_SUBSTR = 'substr'
SOUFFLE_INTRINSIC_PREDS = {SOUFFLE_CONTAINS, SOUFFLE_SUBSTR}

DELIMITER = ', '
EQUAL = ' = '
NEGATION = '!'
NOT_EQUAL = ' != '
EQ_NONEQ = ' eq/neq '
LEFT_SQUARE_BRACKET = '['
RIGHT_SQUARE_BRACKET = ']'

SYMLOG_NUM_POOL_SIZE = 1000
SYMLOG_NUM_POOL = [-sys.maxsize + i for i in range(SYMLOG_NUM_POOL_SIZE)]

SHIMPLE_TEMP_VAR_PREFIX = '$stack'

DEFAULT_GRAPH_ATTR_NAME = 'label'

POS_LIT_LABEL = '+'
NEG_LIT_LABEL = '-'

DL_SCHS = 'schs'
DL_EDBS = 'edbs'
