SYMBOLIC_CONSTANT_PREFIX = '_symlog_symbolic_'
BINDING_VARIABLE_PREFIX = '_symlog_binding_'
DOMAIN_PREDICATE_PREFIX = '_symlog_domain_'
DEFAULT_SOUFFLE_TYPE = 'symbol'

DELIMITER = ', '
EQUAL = ' = '
NEGATION = '!'
NOT_EQUAL = ' != '
EQ_NONEQ = ' eq/neq '
LEFT_SQUARE_BRACKET = '['
RIGHT_SQUARE_BRACKET = ']'
